name: dropletML

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - conda-forge::python=3.9
  - conda-forge::opencv
  - conda-forge::numpy
  - conda-forge::tqdm
  - conda-forge::tensorboard
  - conda-forge::pyyaml
  - conda-forge::scikit-learn
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch-cuda=12.4