name: dropletML

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python
  - opencv
  - numpy
  - tqdm
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch-cuda
  - tensorboard